apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: import-tests-go-ygvjjasb-import
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/import-tests-go-ygvjjasb-import:4fae4571557de6255b3eea95d7728195fc4ff934
          name: container-image
